require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('./firebase');
const authRoutes = require('./routes/auth');
const shopRoutes = require('./routes/shop');
const ekeyRoutes = require('./routes/ekey');
const toolsRoutes = require('./routes/tools');
const topupRoutes = require('./routes/topup');
const gameRoutes = require('./routes/game');
const adminRoutes = require('./routes/admin');
const { requireAdminSecret } = require('./middleware/auth');
const { generalLimiter, authLimiter, moneyLimiter, adminLimiter } = require('./middleware/rateLimits');
const { notFound, errorHandler } = require('./middleware/error');
const app = express();
const origins = String(process.env.CORS_ORIGINS || '').split(',').map(s => s.trim().replace(/\/$/, '')).filter(Boolean);
function corsOk(origin) { if (!origin) return true; if (origins.includes('*')) return true; try { const u = new URL(origin); return origins.includes(origin.replace(/\/$/, '')) || origins.includes(u.origin); } catch { return false; } }
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin(origin, cb) { corsOk(origin) ? cb(null, true) : cb(new Error('CORS denied: ' + origin)); }, credentials: false }));
app.options('*', cors());
app.use(express.json({ limit: '250kb' }));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(generalLimiter);
app.get('/', (req,res)=>res.json({ ok:true, service:'random19k-api-v2' }));
app.get('/api/health', (req,res)=>res.json({ ok:true, service:'random19k-api-v2' }));
app.use('/api/auth', authLimiter, authRoutes);
app.use('/api', shopRoutes);
app.use('/api/ekey', moneyLimiter, ekeyRoutes);
app.use('/api/tools', moneyLimiter, toolsRoutes);
app.use('/api/topup', moneyLimiter, topupRoutes);
app.use('/api/game', moneyLimiter, gameRoutes);
app.use('/api/admin', adminLimiter, requireAdminSecret, adminRoutes);
app.use(notFound);
app.use(errorHandler);
const port = Number(process.env.PORT || 3000);
app.listen(port, '0.0.0.0', () => console.log('random19k API v2 running on port ' + port));
